openapi: '3.0.2'
info:
  title: argos-repository-cache
  version: '1.0'
servers:
  - url: http://localhost
paths:
  /repositories/user/repo/tag:
    get:
      description: 'retrieves archive from user, repo and tag'
      responses:
        '200':
          description: OK
    post:
      description: 'adds an archive and a json metadata file at /user/repo/tag'
      responses:
        '200':
          description: OK
  /repositories/user/repo/tag/metadata:
    get:
      description: 'retrieves metadata about archive stored at /user/repo/tag'
      responses:
        '200':
          description: 'data'
