openapi: '3.0.2'
info:
  title: argos-repository-cache
  version: '1.0'
servers:
  - url: http://localhost
paths:
  /repositories/garbagemza/repo/tag:
    get:
      description: 'retrieves archive from user, repo and tag'
      responses:
        '200':
          description: OK
    post:
      description: 'adds an archive and stores a json metadata file'
      responses:
        '200':
          description: OK
